### ISSUE TITLE
Reg: Number of connections getting increased after sevral retries

### ISSUE THREAD

**Issue by iamsireesh** [marshallformula/mongoose-persistent-connector#1]
I used your library, everything is working fine, but one issue which i found out is, after few retries and enable the mongo server, it got connected, but when i look into number of connections in mongo (db.serverStatus()), It is showing around 50+ connections.

**Comment by marshallformula** [comment]
Good catch @iamsireesh .  After a little more digging I realized this package is just duplicating functionality that already exists in the mongo driver.  

[http://mongodb.github.io/node-mongodb-native/api-generated/db.html#id1](http://mongodb.github.io/node-mongodb-native/api-generated/db.html#id1)

You can specify both `retryMiliSeconds` and `numberOfRetries` in the options object passed to `mongoose.connect`to get the effect I was trying for here.  In light of that functionality - I will be deprecating this module in npm.  

FYI.  I have noticed in my testing that the mongo driver connection events are a bit finicky.  Specifically if the the connection fails on the first try - it will not fire subsequent 'connected/reconnected' events - even though by monitoring the mongodb you can see that it does indeed reconnect.

**Comment by iamsireesh** [comment]
Hi @marshallformula , I tried with retryMiliSeconds and numberOfRetries in addition to the same functionality, there is no effect on the behaviour.

I have removed the connectDB call in reconnected event, After 60 seconds, the program is getting terminated and events are not getting fired even the retryMiliSeconds and numberOfRetries combination is more than 60 seconds.

**Comment by iamsireesh** [comment]
Hi @marshallformula ,
           We can use MongoDB native driver options to configure this, No need to call connectDB method in disconnected event
server: {
        auto_reconnect: true,
        reconnectInterval: 5000,
        reconnectTries: Infinity,
        socketOptions: {
            keepAlive: 1
        }
 }

FYI: http://mongodb.github.io/node-mongodb-native/2.0/api/Server.html

**Comment by marshallformula** [comment]
Hi @iamsireesh 

That's essentially exactly what I was attempting to say in my reply earlier.  `retryMiliSeconds` and `numberOfRetries` are options used in the native driver.    This is why I deprecated this project - because the functionality already exists in the native driver.  Just use the the native options instead of this library.
